export const POST_ADD = "POST_ADD"
export const POST_UPDATE = "POST_UPDATE"
export const POST_REMOVE = "POST_REMOVE"

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'

export const FETCH_MINI_POST_REQUEST = 'FETCH_MINI_POST_REQUEST'
export const FETCH_MINI_POST_SUCCESS = 'FETCH_MINI_POST_SUCCESS'
export const FETCH_MINI_POST_FAILURE = 'FETCH_MINI_POST_FAILURE'

export const FETCH_TAGE_REQUEST = 'FETCH_TAGE_REQUEST'
export const FETCH_TAGE_SUCCESS = 'FETCH_TAGE_SUCCESS'
export const FETCH_TAGE_FAILURE = 'FETCH_TAGE_FAILURE'