export const PAGE_ADD = "PAGE_ADD"
export const PAGE_UPDATE = "PAGE_UPDATE"
export const PAGE_REMOVE = "PAGE_REMOVE"

export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST'
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS'
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE'