export const POST_ADD = "POST_ADD"
export const POST_UPDATE = "POST_UPDATE"
export const POST_REMOVE = "POST_REMOVE"

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'