export const NAV_SELECT = "NAV_SELECT"
export const NAV_SELECT_BY_PATHG = "NAV_SELECT_BY_PATHG"

export const FETCH_LOGO_REQUEST = 'FETCH_LOGO_REQUEST'
export const FETCH_LOGO_SUCCESS = 'FETCH_LOGO_SUCCESS'
export const FETCH_LOGO_FAILURE = 'FETCH_LOGO_FAILURE'